# Generated by Django 5.0.2 on 2024-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="name",
            field=models.CharField(default="undefined", max_length=100),
        ),
    ]
